trigger:
- master

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  pool: Azure
  jobs:  
  - job: Pack
    displayName: Pack
    steps:
    - task: DotNetCoreCLI@2
      displayName: Dotnet Pack
      inputs:
        command: 'pack'
        packagesToPack: '**/*pack.csproj'
        versioningScheme: byBuildNumber
    - task: NuGetCommand@2
      displayName: 'NuGet push nuget'
      inputs:
        command: push
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: external
        publishFeedCredentials: nuget